name: lwk_dart_example
description: "Demonstrates how to use the lwk_dart plugin."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  lwk_dart: 
    path: ../
    # git:
    #   url: https://github.com/SatoshiPortal/lwk-dart.git
    #   ref: trunk
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
