[package]
name = "lwk-bridge"
description = "Flutter-Rust Bridge for Liquid Wallet Kit (lwk)"
authors = ["i5hi <ishi@satoshiportal.com>, mocodesmo <morteza@satoshiportal.com>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "lwkbridge"
doctest = false
crate-type = ["staticlib", "cdylib"] 

[dependencies]
lwk_wollet = { git = "https://github.com/Blockstream/lwk.git", package = "lwk_wollet" }
lwk_signer = { git = "https://github.com/Blockstream/lwk.git", package = "lwk_signer" }
lwk_common = { git = "https://github.com/Blockstream/lwk.git", package = "lwk_common" }
thiserror = "1.0.50"
elements = "0.24.0"
flutter_rust_bridge = "1.82.2"
anyhow = "1.0.68"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.82.6"  }


[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[patch.crates-io]
elements-miniscript = { git = "https://github.com/ElementsProject/elements-miniscript.git", rev = "31fbf2748e6649790a0cf1e4d0f972b3ff1db171" }