[package]
name = "lwk-dart"
authors = ["i5hi <ishi@satoshiportal.com>, mocodesmo <morteza@satoshiportal.com>"]
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
crate-type = ["staticlib", "cdylib"] 

[dependencies]
lwk_wollet = "0.2.0"
lwk_signer = "0.2.0"
lwk_common = "0.2.0"
thiserror = "1.0.50"
elements = "0.24.0"
flutter_rust_bridge = "1.82.2"
anyhow = "1.0.68"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.82.6"  }


[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
